import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/bookmarks/main';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Bookmarks',
  description: 'Browse your bookmarks.',
};

const Resources = () => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main />
    </>
  );
};
export default Resources;
