import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/reset/main';
import { verifyToken } from '@/utils/jwtUtils';
import { checkServerSession } from '@/utils/serserSideUtils';
import { NextApiRequest, NextApiResponse } from 'next';

const Reset = ({
  payload,
  error,
}: {
  payload?: {
    id: string;
    email?: string;
    exp: number;
  };
  error?: string;
}) => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main payload={payload} error={error} />
    </>
  );
};

export default Reset;

export const getServerSideProps = async ({
  req,
  res,
  query,
  locale,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
  query: any;
  locale: any;
}) => {
  const user = await checkServerSession(req, res);

  const { token } = query;

  if (user) {
    return {
      redirect: {
        destination: '/',
        statusCode: 302,
      },
    };
  }

  let payload, error;
  try {
    payload = verifyToken(token);
  } catch (err: any) {
    console.log(err);
    error = err;
  }

  return {
    props: {
      ...(payload && { payload: payload }),
      ...(error && { error: error?.message }),
    },
  };
};
