import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/admin/analytics/main';
import { checkServerSession } from '@/utils/serserSideUtils';

import { NextApiRequest, NextApiResponse } from 'next';

const Analytics = () => {
  return (
    <>
      <Meta title="Costudy" description="Generated by create next app" />
      <Main />
    </>
  );
};
export default Analytics;

export const getServerSideProps = async ({
  req,
  res,
  locale,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
  locale: string;
}) => {
  const user = await checkServerSession(req, res);

  if (!user) {
    return {
      redirect: {
        destination: '/login',
        statusCode: 302,
      },
    };
  }
  if (user?.type !== 'admin') {
    return {
      redirect: {
        destination: '/',
        statusCode: 403,
      },
    };
  }
  return {
    props: {},
  };
};
