import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/title/main';
import { Resource } from '@/types/types';
import { prisma } from '@/utils/prisma';
import { NextApiRequest, NextApiResponse } from 'next';
import { NextApiRequestQuery } from 'next/dist/server/api-utils';

const ResourcePage = ({ resource }: { resource: Resource }) => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main resource={resource} />
    </>
  );
};

export default ResourcePage;

export const getServerSideProps = async ({
  req,
  res,
  query,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
  query: NextApiRequestQuery;
}) => {
  const { type, title } = query;

  try {
    const resource = await prisma.resource.findUnique({
      where: {
        title: (title as string)?.replaceAll(/\-/g, ' ').replaceAll(/\_/g, '|'),
      },
    });

    if (!resource) {
      return {
        notFound: true,
      };
    }
    return {
      props: {
        resource: {
          ...resource,
          createdAt: resource?.createdAt.toISOString(),
          updatedAt: resource?.updatedAt.toISOString(),
        },
      },
    };
  } catch (error: any) {
    console.log(error);
    return {
      notFound: true,
    };
  }
};
