import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/home/main';
import { Resource } from '@/types/types';
import { helpers } from '@/utils/helpers';
import { NextApiRequest, NextApiResponse } from 'next';

const Home = ({
  resources,
  error,
}: {
  resources: Resource[];
  error: string;
}) => {
  const cards = [
    {
      id: '3Tazg',
      title: 'Processor Archetecture',
      type: 'docx',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: '3Tazg',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: 'gQGq',
      title: 'Processor Archetecture',
      type: 'video',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: 'zg',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: '3Tzzgzgg',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: '3Tzzhsdhfhgg',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: 'gdgg',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: 'gzgz',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
    {
      id: 'jrkj',
      title: 'Processor Archetecture',
      type: 'pdf',
      class: 'Assembly Language Programming',
      major: 'Computer Science and Technology',
      degree: 'Bachelor',
      year: '2st',
      by: 'Lazy Dev',
    },
  ];

  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main resources={resources} error={error} />
    </>
  );
};

export default Home;

export const getServerSideProps = async ({
  req,
  res,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
}) => {
  const data = await (await helpers({ req, res })).resources.home.get.fetch();

  const resources = data?.map((resource) => {
    let data;
    data = {
      ...resource,
      createdAt: resource?.createdAt?.toLocaleDateString(),
      updatedAt: resource?.updatedAt?.toLocaleDateString(),
    };
    return data;
  });

  return {
    props: {
      resources: resources || [],
      // resources: [],
    },
  };
};
