import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/home/main';

const Home = () => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main />
    </>
  );
};

export default Home;
