import Meta from '@/components/commun/static/Meta';
import Spinner from '@/components/commun/static/spinner';
import Main from '@/components/modules/reset/main';
import { isLoggedIn } from '@/utils/serserSideUtils';
import { Suspense } from 'react';

const Reset = async ({
  params,
}: {
  params: {
    token: string;
  };
}) => {
  await isLoggedIn({ login: true });

  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Suspense
        fallback={
          <div className="w-full h-[500px] flex flex-col justify-center items-center gap-2 ">
            <p>Checking the token...</p>
            <Spinner className="text-[#8449BF] h-8 w-8" />
          </div>
        }
      >
        <Main token={params.token} />
      </Suspense>
    </>
  );
};

export default Reset;
