import { checkServerSession } from '@/utils/serserSideUtils';
import { NextApiRequest, NextApiResponse } from 'next';

import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/login/main';

export const getServerSideProps = async ({
  req,
  res,
  query,
  locale,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
  query: any;
  locale: any;
}) => {
  const user = await checkServerSession(req, res);

  if (user) {
    return {
      redirect: {
        destination: '/',
        statusCode: 302,
      },
    };
  }

  return {
    props: {},
  };
};

const LogIn = () => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main />
    </>
  );
};

export default LogIn;
