import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/admin/analytics/main';
import { isAdmin } from '@/utils/serserSideUtils';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Analytics | CoStudy',
  description: '',
};

const Analytics = async () => {
  await isAdmin();
  return (
    <>
      <Meta title="Costudy" description="Generated by create next app" />
      <Main />
    </>
  );
};
export default Analytics;
