import { NextApiRequest, NextApiResponse } from 'next';
import Head from 'next/head';
import Main from '@/components/modular/register/main';
import { checkServerSession } from '@/utils/serserSideUtils';

export const getServerSideProps = async ({
  req,
  res,
  query,
  locale,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
  query: any;
  locale: any;
}) => {
  const user = await checkServerSession(req, res);
  if (user) {
    return {
      redirect: {
        destination: '/',
        statusCode: 302,
      },
    };
  }

  return {
    props: {},
  };
};

const SignUp = () => {
  return (
    <>
      <Head>
        <title>Co Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
};

export default SignUp;
