import Meta from '@/components/commun/static/Meta';
import Image from 'next/image';

import { Label } from '@/components/ui/label';
import SupportImg from '@/public/support-img.svg';

import TicketForm from '@/components/modules/support/TicketForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Support',
  description: 'Track your website status.',
};

const Support = () => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <div
        className=" w-full h-full flex flex-col justify-start items-center
                 pr-2 pl-2 md:pr-6 md:pl-6 gap-10 pb-20"
      >
        <div className="w-4/6 md:w-2/6 h-auto">
          <Image
            src={SupportImg}
            alt="we are here for you"
            width={100}
            height={100}
            quality={100}
            className="w-full h-full"
          />
        </div>
        <div className=" w-full h-auto md:pr-24 md:pl-24 flex">
          <span className="text-2xl md:text-4xl font-bold rotate-[20deg] mr-2 ml-2 text-black">
            +
          </span>
          <p className="text-xl md:text-3xl font-bold text-[#8449BF]">
            Troubleshooting Tips
          </p>
        </div>
        <div
          className=" w-full h-auto pr-4 pl-4 md:pr-28 md:pl-28 flex flex-col justify-center items-start
            gap-3"
        >
          <p className="text-md md:text-lg text-black font-bold">
            Login Issues
          </p>
          <p className="text-sm md:text-md text-black font-normal">
            <span className="font-bold">Solution:</span> Provide steps to reset
            passwords, check for correct login credentials, and clear browser
            cache if necessary. Offer guidance on enabling two-factor
            authentication (2FA) for enhanced security.
          </p>
          <p className="ttext-md md:text-lg text-black font-bold">
            Slow Page Load Times
          </p>
          <p className="text-sm md:text-md text-black font-normal">
            <span className="font-bold">Solution:</span> Instruct users to check
            their internet connection, clear browser cache, and ensure they are
            using a compatible browser. You can also recommend trying a
            different device or checking for background applications that might
            be using up bandwidth.
          </p>
          <p className="text-md md:text-lg text-black font-bold">
            Unable to Download Files
          </p>
          <p className="text-sm md:text-md text-black font-normal">
            <span className="font-bold">Solution:</span> I Walk users through
            the file download process, ensuring they are using supported file
            formats and sizes. Verify if their internet connection is stable,
            and suggest using an alternative browser if the issue persists.
          </p>
          <p className="text-md md:text-lg text-black font-bold">
            Lost Data or Content
          </p>
          <p className="text-sm md:text-md text-black font-normal">
            <span className="font-bold">Solution:</span> Advise users on data
            backup practices and explain how to retrieve content from their
            account's backup if applicable. Encourage regular manual backups and
            educate them on the importance of saving work frequently.
          </p>
          <p className="text-lg text-black font-bold">
            Inability to Join Study Rooms
          </p>
          <p className="text-sm md:text-md text-black font-normal">
            <span className="font-bold">Solution:</span> Offer instructions on
            how to join study rooms, including troubleshooting steps for common
            issues like browser compatibility, cookies, and ensuring the room is
            not at capacity. Suggest trying again at a different time.
          </p>{' '}
          <p className="text-md md:text-lg text-black font-bold">
            Notification or Email Issues
          </p>
          <p className="text-sm md:text-md text-black font-normal">
            <span className="font-bold">Solution:</span> Explain how to manage
            notification preferences within their account settings. Instruct
            users to check their spam or junk folder for missed emails and add
            your domain to their email whitelist.
          </p>
        </div>
        <div className="w-full h-auto mt-4 md:mt-12 pr-4 pl-4 md:pr-32 md:pl-32 flex flex-col justify-center items-center">
          <Label className="text-2xl md:text-4xl  font-semibold w-full text-center">
            Contact Us!
          </Label>
          <p className="md:w-4/5  text-xs md:text-lg text-center">
            Feel free to share your thoughts and opinions, doubts and concerns
            and we will get back at you as soon as possible. We are waiting for
            you feedback!
          </p>
        </div>
        <TicketForm />
      </div>
    </>
  );
};
export default Support;
