import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/title/main';
import { Resource } from '@/types/types';
import { prisma } from '@/utils/prisma';

const ResourcePage = async ({ params }: { params: { title: string } }) => {
  const { title } = params;

  const resource = await prisma.resource.findUnique({
    where: {
      title: (title as string)?.replaceAll(/\-/g, ' ').replaceAll(/\_/g, '|'),
    },
  });

  if (!resource) {
    return {
      notFound: true,
    };
  }

  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main resource={resource! as unknown as Resource} />
    </>
  );
};

export default ResourcePage;
