import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/resources/main';

const Resources = () => {
  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main />
    </>
  );
};
export default Resources;
