import Meta from '@/components/commun/static/Meta';
import Main from '@/components/modules/login/main';
import { isLoggedIn } from '@/utils/serserSideUtils';

const LogIn = async () => {
  await isLoggedIn({ login: true });

  return (
    <>
      <Meta title="Co Study" description="Generated by create next app" />
      <Main />
    </>
  );
};

export default LogIn;
